import '../styles/globals.css'
import "../styles/Footer.scss"
import type { AppProps } from 'next/app'
import { store, wrapper } from '../store/store'
import { Provider } from 'react-redux'
import Head from 'next/head'
import LeftSideBar from '../components/LeftSideBar/LeftSideBar'
import TopNavBar from '../components/TopNavBar/TopNavBar'
import { RightIcon } from '../assets/icons'
import RightNavBar from '../components/RightNavBar/RightNavBar'
import FooterNav from '../components/FooterNav/FooterNav'
import { ReactElement, ReactNode, useEffect, useState } from 'react'
import { NextPage } from 'next'
import useApp from '../pageUtils/useApp'
import { QueryClientProvider, QueryClient } from 'react-query'
import AppSetup from '../components/AppSetup/AppSetup'


export type NextPageWithLayout<P = {}, IP = P> = NextPage<P, IP> & {
    getLayout?: (page: ReactElement) => ReactNode
}

type AppPropsWithLayout = AppProps & {
    Component: NextPageWithLayout
}

const client = new QueryClient()

function App({ Component, pageProps }: AppPropsWithLayout) {
    const { } = useApp()

    if (Component.getLayout) return Component.getLayout(<Component {...pageProps} />)

    return (
        <Provider store={store}>
            <QueryClientProvider client={client} >
                <AppSetup />
                <Head>
                    <title>Litumba - The Bakwerian online platform</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.png" />
                </Head>
                <div id='app' className={` overflow-hidden grid  h-[100vh]  grid-rows-[64px_auto_50px] sm:grid-cols-[auto_300px] min-[994px]:grid-rows-[minmax(0px,max-content)_auto] min-[994px]:grid-cols-[minmax(0px,max-content)_auto_minmax(0px,max-content)] max-w-[2000px] m-auto border-solid border-border border-[1.5px]`}>
                    <div className=' hidden min-[994px]:block md:row-span-2 md:h-full md:overflow-auto '><LeftSideBar /></div>
                    <div className='sm:col-span-2 h-[50px] max-h-[150px] relative'><TopNavBar /></div>
                    <div className=' h-full overflow-x-hidden overflow-y-auto ' id='page-component'><Component {...pageProps} /></div>
                    <div id="app_menu" className='hidden top-0 left-0 z-10 h-screen overflow-scroll w-full max-[640px]:max-w-fit sm:relative sm:block sm:h-full sm:overflow-scroll max-w-sm p-2 '><RightNavBar /></div>
                    <div className=' sm:col-span-2 min-[994px]:hidden w-full self-end'><FooterNav /></div>
                </div>
            </QueryClientProvider>
        </Provider>
    )
}

export default App