import '../styles/globals.css'
import "../styles/Footer.scss"
import type { AppProps } from 'next/app'
import { store, wrapper } from '../store/store'
import { Provider } from 'react-redux'
import Head from 'next/head'
import LeftSideBar from '../components/LeftSideBar/LeftSideBar'
import TopNavBar from '../components/TopNavBar/TopNavBar'
import { RightIcon } from '../assets/icons'
import RightNavBar from '../components/RightNavBar/RightNavBar'
import FooterNav from '../components/FooterNav/FooterNav'

function App({ Component, pageProps }: AppProps) {

    return (
        <Provider store={store}>
            <Head>
                <title>Litumba - The Bakwerian online platform</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.png" />
            </Head>
            <div className='grid h-[100vh]  grid-rows-[auto_auto_auto] sm:grid-cols-2 md:grid-rows-[auto auto] md:grid-cols-[auto_auto_auto] max-w-[2000px] m-auto border-solid border-border border-[1.5px]'>
                <div className=' hidden md:block md:row-span-2 md:h-full md:overflow-scroll '><LeftSideBar /></div>
                <div className='sm:col-span-2 md:col-span-2'><TopNavBar /></div>
                <div className=' h-full overflow-scroll'><Component {...pageProps} /></div>
                <div className='hidden sm:block sm:h-full sm:overflow-scroll max-w-sm'><RightNavBar /></div>
                <div className=' sm:col-span-2 md:hidden'><FooterNav /></div>
            </div>
        </Provider>
    )
}


// * export default wrapper.withRedux(App) // this should serve as a reference to demonstrate how to wrap an a next app with next-redux-wrapper
export default App