import '../styles/globals.css'
import "../styles/Footer.scss"
import type { AppProps } from 'next/app'
import { store, wrapper } from '../store/store'
import { Provider } from 'react-redux'
import Head from 'next/head'

function App({ Component, pageProps }: AppProps) {

    return (
        <Provider store={store}>
            <Head>
                <title>Litumba - The Bakwerian online platform</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.png" />
            </Head>
            <Component {...pageProps} />
        </Provider>
    )
}


// * export default wrapper.withRedux(App) // this should serve as a reference to demonstrate how to wrap an a next app with next-redux-wrapper
export default App