import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a >Litumba!</a>
        </h1>
        <p className='text-red-500 font-semibold'>
            this is a platform in which Bakwerians can meet and share and help each other.
        </p>
      </main>

   
    </div>
  )
}
